api/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.getRecipes, name="get-recipes"),
    path('create/', views.createRecipe, name="create-recipe"),
    path('view/<slug:slug>/', views.viewRecipe, name="view-recipe"),
    path('delete/<slug:slug>/', views.deleteRecipe, name="delete-recipe"),
    path('update/<slug:slug>/', views.updateRecipe, name="update-recipe"),
    path('view/<slug:slug>/comment/', views.createComment, name="create-comment"),
    path('comments/', views.getComments, name="comments")
]

cookbook/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipes.urls")),
    path('api/', include('api.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views



app_name = "recipes"
urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', views.blog, name="blog"),
    path("create/", views.createRecipe, name="create"),
    path("update/<slug:slug>/", views.updateRecipe, name="update"),
    path("delete/<slug:slug>/", views.deleteRecipe, name="delete"),
    path("view/<slug:slug>/", views.viewRecipe, name="view"),
    path("view/comment/<slug:slug>/", views.createComment, name="comment"),
    path('', include('django.contrib.auth.urls')),
    path('login/', views.loginView, name="login"),
    path('demo-login/', views.demoLogin, name="demo-login"),
]

recipes/models.py
from django.db import models
from recipes.choices import *
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify


class Recipe(models.Model):        
    title = models.CharField(max_length=150)
    date = models.DateTimeField(auto_now_add=True)
    image = models.URLField(null=True, blank=True, default="https://i0.wp.com/images-prod.healthline.com/hlcmsresource/images/AN_images/healthy-eating-ingredients-1296x728-header.jpg?w=1155&h=1528")
    cuisine = models.CharField(null=True, blank=True, max_length=20, choices=CUISINE_CHOICES, default='None')
    meal = models.CharField(null=True, blank=True, max_length=20, choices=MEAL_CHOICES, default='None')
    description = models.TextField(null=True, blank=True)
    prep_time = models.IntegerField()
    cook_time = models.IntegerField()
    servings = models.IntegerField()
    ingredients = models.TextField(null=True, blank=True)
    instructions = models.TextField(null=True, blank=True)
    slug = models.SlugField(blank=True, null=True, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipes:view', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs): 
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Comment(models.Model): 
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    comment = models.CharField(max_length=240) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 

    class Meta: 
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.recipe) 

recipes/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Recipe, Comment
from recipes.choices import *


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'

    def clean_servings(self):
        value = self.cleaned_data.get("servings")
        print(value)
        if value < 1:
            raise forms.ValidationError("The number of servings must be greater than zero.")
        return value

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'comment',)

recipes/views.py
from django.http.response import JsonResponse
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import RecipeForm, CommentForm
from .filters import RecipeFilter
from django.core.paginator import Paginator
from .models import Recipe, Comment
from django.db.models import Q
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from rest_framework.response import Response

def index(request):
    recipes = Recipe.objects.all().order_by('-date')

    if request.user.is_authenticated:
            return render(request, "recipes/index.html", {
            "recipes": recipes,
        })
    else:
        return redirect('/login/')
    

def blog(request):
    recipes = Recipe.objects.all().order_by('date')
    if "recipes" not in request.session:
        request.session["recipes"] = []

    filter = RecipeFilter(request.GET, queryset=Recipe.objects.all())
    recipes = filter.qs

    paginator = Paginator(recipes, 15)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)



    return render(request, "recipes/blog.html", {
        "recipes": recipes,
        "filter": filter,
        'page_obj':page_obj
    })

def viewRecipe(request, slug):
    filter = RecipeFilter(request.GET, queryset=Recipe.objects.all())
    recipe = Recipe.objects.get(slug=slug)

    comments = recipe.comments.filter(active=True)
    comment_form = CommentForm()
    new_comment = None

    return render(request, 'recipes/view.html', {
            "recipe": recipe,
            "filter": filter,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form
        })

def createRecipe(request):
    recipes = Recipe.objects.all()
    filter = RecipeFilter(request.GET, queryset=Recipe.objects.all())

    if request.method == "GET":
        form = RecipeForm(initial = {
            'ingredients': "- ",
            'instructions': "1. ",
        })
        return render(request, "recipes/add.html", {
            "form":form,
            "filter": filter
        })

    elif request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            recipe = form.cleaned_data.get("recipe")
            return redirect('/')

        else:    
            return render(request, "recipes/add.html", {
                "form": form,
        })

    return render(request, "recipes/add.html", {
        "filter": filter
    })

def updateRecipe(request, slug):
    recipe = Recipe.objects.get(slug=slug)

    if request.method == 'GET':
        form = RecipeForm(initial = {
            'title': recipe.title,
            'image': recipe.image,
            'cuisine': recipe.cuisine,
            'meal': recipe.meal,
            'description': recipe.description, 
            'prep_time': recipe.prep_time,
            'cook_time': recipe.cook_time,
            'servings': recipe.servings,
            'ingredients': recipe.ingredients,
            'instructions': recipe.instructions,
        })
    elif request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, instance=recipe)

        if form.is_valid():
            form.save()
            recipe = form.cleaned_data.get("recipe")
            return redirect('recipes:view', slug)

        else:    
            return render(request, "recipes/update.html", {
                "form": form,
                "recipe": recipe,
        })

    return render(request, "recipes/update.html", {
        "form": form,
        "recipe": recipe,
    })

def deleteRecipe(request, slug):
    recipe = Recipe.objects.get(slug=slug)
    comments = recipe.comments.filter(active=True)
    comment_form = CommentForm()
    new_comment = None

    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        recipe.delete()
        
        return redirect('/')

def createComment(request, slug):
    filter = RecipeFilter(request.GET, queryset=Recipe.objects.all())
    recipe = Recipe.objects.get(slug=slug)
    new_comment = None
    comment_form = CommentForm(data=request.POST)
    if comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        new_comment.recipe = recipe
        new_comment.save()
    
    comments = recipe.comments.filter(active=True)

    return render(request, 'recipes/view.html', {
        'recipe': recipe,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form
    })

def loginView(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'recipes/index.html', {'form': form})

def demoLogin(request):
    if request.method == 'POST':
        username = 'demo_user'
        password = 'demo_password'
        user = authenticate(request, username=username, password=password)
        login(request, user)
        return redirect('/')

def logout(request):
    return render(request, 'recipes/index.html', {})

recipes/templates/recipes/add.html
{% extends "recipes/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block body %}
    <h1 class="text-center">Add a Recipe</h1>

  <div class="container">
    <form action="{% url 'recipes:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.title|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.image|as_crispy_field }}
            </div>
          </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.cuisine|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.meal|as_crispy_field }}
            </div>
        </div>
        {{ form.description|as_crispy_field }}
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
              {{ form.prep_time|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
              {{ form.cook_time|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.servings|as_crispy_field }}
            </div>
        </div>
        {{ form.ingredients|as_crispy_field }}
        {{ form.instructions|as_crispy_field }}

        <button type="submit" class="btn btn-dark mt-2">Submit</button>
    </form>
  </div>
{% endblock %}

recipes/templates/recipes/blog.html
{% extends "recipes/layout.html" %}
{% load static %}
 
{% block body %}
<div class="container mt-3">
    <h2 class="text-center py-3">RECIPE BLOG</h2>
  <div class="row">
      <div class="col-lg-8">
        {% for recipe in page_obj %}
        {% if page_obj is None %}
            <h2>No recipes found</h2>
        {% else %}
        {% if forloop.first %}
          <div class="card mb-4">
              <a href="{% url 'recipes:view' slug=recipe.slug %}"><img class="card-img-top-main" src="{{ recipe.image }}" alt="..." /></a>
              <div class="card-body">
                  <div class="small text-muted">{{ recipe.date }}</div>
                  <a href="{% url 'recipes:view' slug=recipe.slug %}"><h2 class="card-title">{{ recipe.title}}</h2></a>
                  <p class="card-text">{{ recipe.description}}</p>
              </div>
          </div>
          <div class="row">
            {% else %}
              <div class="col-lg-6 d-flex align-items-stretch">
                  <div class="card mb-4">
                      <a href="{% url 'recipes:view' slug=recipe.slug %}"><img class="card-img-top" src="{{ recipe.image }}" alt="..." /></a>
                      <div class="card-body d-flex flex-column">
                          <div class="small text-muted">{{ recipe.date }}</div>
                          <a href="{% url 'recipes:view' slug=recipe.slug %}"><h2 class="card-title h4">{{ recipe.title}}</h2></a>
                          <p class="card-text">{{ recipe.description}}</p>
                      </div>
                  </div>
              </div>
            {% endif %}
            {% endif %}
            {% endfor %}
          </div>
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                    </li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            </ul>
          </nav> 
          
      </div>
      <div class="col-lg-4">
          <div class="card mb-4">
              <div class="card-header">Search</div>
              <div class="card-body py-2">
                  <div class="input-group">
                    <form class="form-inline my-2 my-lg-0" action="{% url 'recipes:index' %}" method="GET">
                      {{ filter.form.search }}
                      <button class="btn btn-dark rounded-pill my-2 my-sm-0" type="submit">Search</button>
                    </form>
                  </div>
              </div>
          </div>
          <div class="card mb-4">
              <div class="card-header">Categories</div>
              <div class="card-body">
                  <div class="row">
                      <div class="col-sm-6">
                          <ul class="list-unstyled mb-0">
                              <li><a href="{% url 'recipes:blog' %}?cuisine=American&meal=">American</a></li>
                              <li><a href="{% url 'recipes:blog' %}?cuisine=Asian&meal=">Asian</a></li>
                              <li><a href="{% url 'recipes:blog' %}?cuisine=Indian&meal=">Indian</a></li>
                              <li><a href="{% url 'recipes:blog' %}?cuisine=Mexican&meal=">Mexican</a></li>
                          </ul>
                      </div>
                      <div class="col-sm-6">
                          <ul class="list-unstyled mb-0">
                              <li><a href="{% url 'recipes:blog' %}?cuisine=&meal=Breakfast">Breakfast</a></li>
                              <li><a href="{% url 'recipes:blog' %}?cuisine=&meal=Lunch">Lunch</a></li>
                              <li><a href="{% url 'recipes:blog' %}?cuisine=n&meal=Dinner">Dinner</a></li>
                              <li><a href="{% url 'recipes:blog' %}?cuisine=&meal=Snack">Snack</a></li>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

recipes/templates/recipes/delete.html
{% load static %}

<head>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="{% static 'recipes/js/app.js' %}"></script>   
    <link rel="stylesheet" href="{% static 'recipes/css/index.css' %}">
</head>
    <h5 class="modal-title text-center">Are you sure you want to delete "{{recipe.title}}"?</h5>

    <div class="container modal-footer text-center">
        <a href="{% url 'recipes:view' slug=recipe.slug %}"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button></a>
        <form action="{% url 'recipes:delete' slug=recipe.slug %}" method="POST">
            {% csrf_token %}
            <input type="submit" name="Confirm" class="btn btn-primary">
        </form>
    </div>

recipes/templates/recipes/index.html
{% extends "recipes/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block body %}
    <div class="text-center mb-5 mt-3">
        <h1 class="masthead-heading mb-0">COOKBOOK</h1>
        <h2 class="masthead-subheading mb-0">by Hunter Bury</h2>
    </div>
    {% for recipe in recipes %}
    {% if forloop.counter|divisibleby:2 %}
    <section>
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6">
                    <a href="{% url 'recipes:view' slug=recipe.slug %}" class="p-3"><img class="img-fluid rounded-circle" src="{{ recipe.image }}" alt="..." /></a>
                </div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <h2 class="display-4">{{ recipe.title }}</h2>
                        <p>{{ recipe.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    {% else %}
    <section id="scroll">
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <a href="{% url 'recipes:view' slug=recipe.slug %}" class="p-3"><img class="img-fluid rounded-circle" src="{{ recipe.image }}" alt="..." /></a>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <h2 class="display-4">{{ recipe.title }}</h2>
                        <p>{{ recipe.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    {% endfor %}
{% endblock %}

recipes/templates/recipes/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
        <link rel="stylesheet" href="{% static 'recipes/css/index.css' %}">
        <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
        <title>
            Cookbook
        </title>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light py-2">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'recipes:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes:blog' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes:create' %}">Add a Recipe</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'recipes:logout' %}" class="nav-link">Log Out</a>
              </li>
            {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'recipes:login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% block body %}
      {% endblock %}
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-2.1.3.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
      <script src="{% static 'recipes/js/app.js' %}"></script>   
    </body>
    <footer class="mt-2 py-5">
      <div class="social d-flex justify-content-center">
          <a class="mx-2" href="#!"><i class="fab fa-twitter" style="color:black;"></i></a>
          <a class="mx-2" href="#!"><i class="fab fa-facebook-f" style="color:black;"></i></a>
          <a class="mx-2" href="#!"><i class="fab fa-instagram" style="color:black;"></i></a>
      </div>
      <div class="container px-5"><p class="m-0 text-center text-black small">Copyright &copy; Cookbook 2021</p></div>
    </footer>
</html>
   

recipes/templates/recipes/update.html
{% extends "recipes/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block body %}
    <h1 class="text-center">Update Recipe</h1>

  <div class="container">
    <form action="{% url 'recipes:update' slug=recipe.slug %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.title|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.image|as_crispy_field }}
            </div>
          </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.cuisine|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.meal|as_crispy_field }}
            </div>
        </div>
        {{ form.description|as_crispy_field }}
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
              {{ form.prep_time|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
              {{ form.cook_time|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.servings|as_crispy_field }}
            </div>
        </div>
        {{ form.ingredients|as_crispy_field }}
        {{ form.instructions|as_crispy_field }}

        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
  </div>
{% endblock %}

recipes/templates/recipes/view.html
{% extends "recipes/layout.html" %}
 
{% block body %}
<section>
    <div class="container mt-5">
        <div class="row">
            <section class="col-lg-8">
                <article>
                    <header class="mb-4">
                        <h1 class="fw-bolder mb-1">{{ recipe.title }}</h1>
                        <div class="text-muted fst-italic mb-2">{{ recipe.date }}</div>
                        {% if recipe.cuisine %}
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{ recipe.cuisine }}</a>
                        {% endif %}
                        {% if recipe.meal %}
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{ recipe.meal }}</a>
                        {% endif %}
                    </header>
                    <figure class="mb-4"><img class="img-fluid rounded blog-image" src="{{ recipe.image }}" alt="..." /></figure>
                    <section class="mb-5">
                        <p class="fs-5 mb-4">{{ recipe.description }}</p>
                        <h2 class="fw-bolder mb-4 mt-5">Ingredients</h2>
                        <p class="fs-5 mb-4">{{ recipe.ingredients|linebreaks }}</p>
                        <h2 class="fw-bolder mb-4 mt-5">Instructions</h2>
                        <p class="fs-5 mb-4">{{ recipe.instructions|linebreaks }}</p>
                    </section>
                </article>
            </section>
            <div class="col-lg-4 mt-5 py-5">
                <div class="card mb-4">
                    <div class="card-header">Recipe Actions</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="{% url 'recipes:update' slug=recipe.slug %}" class="text-black">Update recipe</a></li>
                                    <li id="myBtn"><a href="#" class="text-black">Delete recipe</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-5 mb-5 comment-section justify-content-center">
        <div class="d-flex justify-content-center row">
            <h2 class="text-center">Comments</h2>
            <div class="d-flex flex-column">
                <div class="coment-bottom p-2 px-4">
                    {% if new_comment %}
                    <h2>Your comment has been added.</h2>
                    {% else %}
                    <div class="row add-comment-section mt-4 mb-4">
                        <h3 class="col-12">Add a comment</h3>
                        <div class="row">
                            <div class="form-inline"><form action="{% url 'recipes:comment' slug=recipe.slug %}" method="post" class="form-inline my-2 my-lg-0">
                                {% csrf_token %}
                                {{ comment_form.name.label_tag }} {{ comment_form.name }}
                                {{ comment_form.comment.label_tag }} {{ comment_form.comment}}
                                <input type="submit" value="Comment" class="btn btn-dark rounded-pill commentBtn">
                            </form></div>
                        </div>
                    </div>
                    {% endif %}
                    {% for comment in comments %}
                    <div class="commented-section mt-2 px-3">
                        <div class="d-flex flex-row align-items-center commented-user">
                            <h5 class="mr-2">{{ comment.name }}</h5><span class="mb-1 ml-2 px-2">{{ comment.created }}</span>
                        </div>
                        <div class="comment-text-sm"><span>{{ comment.comment }}</span></div>
                        <div class="reply-section">
                            <div class="d-flex flex-row align-items-center voting-icons px-1"><i class="fa fa-sort-up fa-2x mt-3 hit-voting"></i><i class="fa fa-sort-down fa-2x mb-3 hit-voting"></i><span class="ml-2 px-1">10</span>
                                <h6 class="px-2 ml-2 mt-1">Reply</h6>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>There are no comments yet.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div id="myModal" class="modal">
        <div class="modal-content container">
            <span class="close">&times;</span>
            <h2>Are you sure you want to delete "{{recipe.title}}"?</h2>
            <div class="container modal-footer text-center">
                <a href="{% url 'recipes:view' slug=recipe.slug %}"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button></a>
                <form action="{% url 'recipes:delete' slug=recipe.slug %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" name="Confirm" class="btn btn-dark">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}